services:
  castor-backend:
    container_name: castor-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  castor-frontend:
    container_name: castor-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - castor-backend
    environment:
      - BACKEND_ORIGIN=http://castor-backend:8080
    ports:
      - "3000:80"
    restart: unless-stopped

